export const WEATHER_DETAILS_REQUEST = 'WEATHER_DETAILS_REQUEST';
export const WEATHER_DETAILS_SUCCESS = 'WEATHER_DETAILS_SUCCESS';
export const WEATHER_DETAILS_ERROR = 'WEATHER_DETAILS_ERROR';

export const NEWS_DETAILS_REQUEST = 'NEWS_DETAILS_REQUEST';
export const NEWS_DETAILS_SUCCESS = 'NEWS_DETAILS_SUCCESS';
export const NEWS_DETAILS_ERROR = 'NEWS_DETAILS_ERROR';

export const REGISTER_USER_DETAILS_REQUEST = 'REGISTER_USER_DETAILS_REQUEST';
export const REGISTER_USER_DETAILS_SUCCESS = 'REGISTER_USER_DETAILS_SUCCESS';
export const REGISTER_USER_DETAILS_ERROR = 'REGISTER_USER_DETAILS_ERROR';
