export const WEATHER_DETAILS_REQUEST = 'WEATHER_DETAILS_REQUEST';
export const WEATHER_DETAILS_SUCCESS = 'WEATHER_DETAILS_SUCCESS';
export const WEATHER_DETAILS_ERROR = 'WEATHER_DETAILS_ERROR';

export const NEWS_DETAILS_REQUEST = 'NEWS_DETAILS_REQUEST';
export const NEWS_DETAILS_SUCCESS = 'NEWS_DETAILS_SUCCESS';
export const NEWS_DETAILS_ERROR = 'NEWS_DETAILS_ERROR';

export const REGISTER_USER_DETAILS_REQUEST = 'REGISTER_USER_DETAILS_REQUEST';
export const REGISTER_USER_DETAILS_SUCCESS = 'REGISTER_USER_DETAILS_SUCCESS';
export const REGISTER_USER_DETAILS_ERROR = 'REGISTER_USER_DETAILS_ERROR';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_ERROR = 'USER_DETAILS_ERROR';

export const SEND_NEWS_DETAILS_REQUEST = 'SEND_NEWS_DETAILS_REQUEST';
export const SEND_NEWS_DETAILS_SUCCESS = 'SEND_NEWS_DETAILS_SUCCESS';
export const SEND_NEWS_DETAILS_ERROR = 'SEND_NEWS_DETAILS_ERROR';

export const GETALL_NEWSDETAILS_REQUEST = 'GETALL_NEWSDETAILS_REQUEST';
export const GETALL_NEWSDETAILS_SUCCESS = 'GETALL_NEWSDETAILS_SUCCESS';
export const GETALL_NEWSDETAILS_ERROR = 'GETALL_NEWSDETAILS_ERROR';

export const PUBLISH_NEWS_ARTICLE_REQUEST = 'PUBLISH_NEWS_ARTICLE_REQUEST';
export const PUBLISH_NEWS_ARTICLE_SUCCESS = 'PUBLISH_NEWS_ARTICLE_SUCCESS';
export const PUBLISH_NEWS_ARTICLE_ERROR = 'PUBLISH_NEWS_ARTICLE_ERROR';
